<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise</title>
</head>

<body>
    <script>
        //Promise/A+规范的三种状态
        const PENDING = 'pending'
        const FULFILLED = 'fulfilled'
        const REJECTED = 'rejected'

        class MyPromise {
            // 构造方法接收一个回调
            constructor(executor) {
                this._status = PENDING     // Promise状态
                this._resolveQueue = []    // 成功队列, resolve时触发
                this._rejectQueue = []     // 失败队列, reject时触发

                // 由于resolve/reject是在executor内部被调用, 因此需要使用箭头函数固定this指向, 否则找不到this._resolveQueue
                let _resolve = (val) => {
                    if(this._status !== PENDING) return   // 对应规范中的"状态只能由pending到fulfilled或rejected"
                    this._status = FULFILLED              // 变更状态

                    // 这里之所以使用一个队列来储存回调,是为了实现规范要求的 "then 方法可以被同一个 promise 调用多次"
                    // 如果使用一个变量而非队列来储存回调,那么即使多次p1.then()也只会执行一次回调
                    while(this._resolveQueue.length) {    
                        const callback = this._resolveQueue.shift()
                        callback(val)
                    }
                }
                // 实现同resolve
                let _reject = (val) => {
                    if(this._status !== PENDING) return   // 对应规范中的"状态只能由pending到fulfilled或rejected"
                    this._status = REJECTED               // 变更状态
                    while(this._rejectQueue.length) {
                        const callback = this._rejectQueue.shift()
                        callback(val)
                    }
                }
                // new Promise()时立即执行executor,并传入resolve和reject
                executor(_resolve, _reject)
            }

            // then方法,接收一个成功的回调和一个失败的回调
            // then方法
            then(resolveFn, rejectFn) {
            //return一个新的promise
                return new MyPromise((resolve, reject) => {
                    //把resolveFn重新包装一下,再push进resolve执行队列,这是为了能够获取回调的返回值进行分类讨论
                    const fulfilledFn = value => {
                        try {
                            //执行第一个(当前的)Promise的成功回调,并获取返回值
                            let x = resolveFn(value)
                            //分类讨论返回值,如果是Promise,那么等待Promise状态变更,否则直接resolve
                            //这里resolve之后，就能被下一个.then()的回调获取到返回值，从而实现链式调用
                            x instanceof MyPromise ? x.then(resolve, reject) : resolve(x)
                        } catch (error) {
                            reject(error)
                        }
                    }
                    //把后续then收集的依赖都push进当前Promise的成功回调队列中(_rejectQueue), 这是为了保证顺序调用
                    this._resolveQueue.push(fulfilledFn)

                    //reject同理
                    const rejectedFn  = error => {
                        try {
                            let x = rejectFn(error)
                            x instanceof MyPromise ? x.then(resolve, reject) : resolve(x)
                        } catch (error) {
                            reject(error)
                        }
                    }
                    this._rejectQueue.push(rejectedFn)
                    switch (this._status) {
                        // 当状态为pending时,把then回调push进resolve/reject执行队列,等待执行
                        case PENDING:
                        this._resolveQueue.push(fulfilledFn)
                        this._rejectQueue.push(rejectedFn)
                        break;
                        // 当状态已经变为resolve/reject时,直接执行then回调
                        case FULFILLED:
                        fulfilledFn(this._value)    // this._value是上一个then回调return的值(见完整版代码)
                        break;
                        case REJECTED:
                        rejectedFn(this._value)
                        break;
                    }
                })
                }

        }

        //All
        /**
         * finally()方法返回一个 Promise。在 promise 结束时，无论结果是 fulfilled 或者是 rejected，都会执行指定的回调函数。
         * 在 finally 之后，还可以继续 then。并且会将值原封不动的传递给后面的 then
         **/
        Promise.prototype.finally = function (callback) {
            return this.then((res) => {
                return Promise.resolve(callback()).then(() => res);
            }, (err) => {
                return Promise.resolve(callback()).then(() => {
                    throw err
                });
            })

        }
        let fn = () => {
            return Promise.reject('这里只有返回被拒绝的 promise 或者 throw 一个错误，才会影响当前 finally 返回的新 promise 的决议')
        }
        var p = Promise.reject('这里只有返回被拒绝的 promise 或者 throw 一个错误，才会影响当前 finally 返回的新 promise 的决议')
            .then(() => {
                return 1
            });

        p.then((res) => {
            console.log('==res', res)
        }, (err) => {
            console.log('=err', err)

        })
        //All
        /**
         * Promise.all(iterable)方法返回一个 Promise 实例，
         * 此实例在 iterable 参数内所有的 promise 都“完成（resolved）”或参数中不包含 promise 时回调完成（resolve）；如果参数中  promise 有一个失败（rejected），
         * 此实例回调失败（reject），失败原因的是第一个失败 promise 的结果。
         **/
        Promise.all = function (arr) {
            let resArr = [];
            let length = 0;
            return new Promise((resolve, reject) => {
                arr.forEach((element, index) => {
                    Promise.resolve(element).then(res => {
                        resArr[index] = res;
                        length++;
                        if (length === arr.length) {
                            resolve(resArr);
                        }
                    }, err => {
                        reject(err);
                    })
                });
            })
        }
        //race
        /**
         * Promise.race(iterable)方法返回一个 promise，
         * 一旦迭代器中的某个 promise 解决或拒绝，返回的 promise 就会解决或拒绝。
         **/
        Promise.race = function (arr) {
            return new Promise((resolve, reject) => {
                arr.forEach(ele => {
                    Promise.resolve(ele).then(resolve(res),reject(err))
                })
            })
        }
        /**
         * 实现 Promise.retry，成功后 resolve 结果，失败后重试，尝试超过一定次数才真正的 reject
         **/
        Promise.retry = function (arr){
            
        } 
    </script>
</body>

</html>